### ISSUE TITLE
DLL Issue? 

### ISSUE THREAD

**Issue by papichulo99** [cralin/repository.cralin#1]
![16863240242006356778310311609035](https://github.com/cralin/repository.cralin/assets/93549391/ba3b5f51-cc04-4732-b5cc-1949ef21f41d)

Am instalat fresh și tot am eroare.

**Comment by cralin** [comment]
Asta este doar repository-ul cu continut.
N-are treaba cu issue-urile legate de pachetele care sint in repository.
