### ISSUE TITLE
Short link

### ISSUE THREAD

**Issue by simonvaly** [cralin/repository.cralin#2]
First , thank you for this nice and useful addon.

Recently I wanted to add this addon on my kodi.
Because Kodi is  installed on a new Gogle Chromecast TV 4k, I do not have possibility to insert a stick with the downloaded zip file.
After this, I tried to identify the correct link for downloading the file from "File management source" in Kodi, but without success.
Could you please provide such a link, which to be added as a source for downloading the repository file?
Thank you.

**Comment by cralin** [comment]
PLease read the "Readme" for this repo
